### ISSUE TITLE
Cannot find module 'node-sass' 

### ISSUE THREAD

**Issue by krutoo** [Connormiha/jest-css-modules-transform#25]
Hi, i use `jest-css-modules-transform` in `.test.tsx` files and i have this error on run tests:

```
Cannot find module 'node-sass'

    Require stack:
      src/common/components/test-component/index.tsx
      src/common/components/test-component/__test__/index.test.tsx

      at getSassContent (node_modules/jest-css-modules-transform/dist/index.js:62:20)
      at Object.process (node_modules/jest-css-modules-transform/dist/index.js:108:27)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:463:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:568:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:606:25)
```

How can i resolve this problem? 
At the moment in my project a do not have `node-sass` dependency in `package.json`.
Should i just add `node-sass`?

**Comment by Connormiha** [comment]
@krutoo  Do you have sass files in your project? `node-sass` requered only for transfromation of `scss/sass` files.

**Comment by krutoo** [comment]
Yes, i have scss file included to my React-component `tsx` file.

**Comment by Connormiha** [comment]
So you have to add `node-sass` in your package.json in devDependencies. Or exclude scss from regexp in your `jest.config.js`.

**Comment by krutoo** [comment]
Ok, thanks. Can this operation be automatic?
