### ISSUE TITLE
Error on import from within prepended file

### ISSUE THREAD

**Issue by tomas-hartman** [Connormiha/jest-css-modules-transform#27]
If I prepend (using prepend option in `jest-css-modules-transform-config.js`) a `.scss` file into which I import some variables from different folder (using relative path), my test up with error:

```
 FAIL tests/js/Footer/Footer.test.jsx
  ● Test suite failed to run
    File to import not found or unreadable: ../../styles/colors.
      at Object.module.exports.renderSync (node_modules/node-sass/lib/index.js:441:16)
      at getSassContent (node_modules/jest-css-modules-transform/dist/index.js:69:24)
      at Object.process (node_modules/jest-css-modules-transform/dist/index.js:108:27)
```

The prepended file (`colors.scss`) is really simple (as is my config file). The prepended file's content is:

```scss
/* This theme currently imports dev styles. */
@import '../../styles/colors';
```

And my `jest-css-modules-transform-config.js`'s content is:

```js
module.exports = {
  prepend: ["./assets/themes/orange/colors.scss"]
};
```

Paths are correct since they work well with `sass-resources-loader` in my webpack, only the secondary import fails. This still could be my fault as I might be missing some sass configuration in the config file, but I am not sure at this point.

**Comment by Connormiha** [comment]
@tomas-hartman thanks for your report. Can you show please your `sass-resources-loader` configuration. I'll try to fix it this week.

**Comment by tomas-hartman** [comment]
@Connormiha Thanks for your reply! My `sass-resources-loader` only uses the very essential:

```js
{
  test: /\.scss$/,
  loader: 'sass-resources-loader',
  options: {
    resources: [
      './assets/themes/orange/colors.scss',
      // some more bootstrap imports etc
    ]
  }
}
```

**Comment by Connormiha** [comment]
@tomas-hartman Try to use absolute path. Something like this:
```js
const path = require('path');

module.exports = {
  prepend: [path.resolve(__dirname, "YOUR_ASSETS_FOLDER" ,"assets/themes/orange/colors.scss")]
};
```

**Comment by tomas-hartman** [comment]
I gave it a try but got the same error as before. There is probably a problem to resolve the (relative) path inside the `colors.scss`.

**Comment by Connormiha** [comment]
@tomas-hartman I reseached this problem. It can be solved with cuscom importer.
`jest-css-modules-transform-config.js`s content is something like this:
```js
module.exports = {
   prepend: ["./assets/themes/orange/colors.scss"],  
   sassConfig: {
     importer: [
         function(url, prev) {
            if (!url.includes("styles/colors")) return null;

            return {
                file: path.resolve(__dirname, "YOUR_ASSETS_FOLDER" ,"styles/colors")
            };
     ],
  }
};
```

More information about importer https://sass-lang.com/documentation/js-api#importer

**Comment by tomas-hartman** [comment]
I finally made it back to this issue in my project, gave it a try and it works! Great! Thank you!
